name: Test code on all platforms
run-name: Test code on all platforms for ${{ github.event_name }} on ${{ github.ref_name }} by ${{ github.actor }}

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Using test-template
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    uses: ./.github/workflows/test-template.yaml
    with:
      runs-on: ${{ matrix.os }}
